name: Sync Fork with Upstream
on: push
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Fetch upstream
        run: |
          git remote add upstream https://github.com/Bakary98/NukuData.git
          git fetch upstream
      - name: Merge changes from upstream
        run: git merge upstream/main
      - name: Push changes to origin
        run: git push origin main