name: Sync Fork with Upstream
on: [push]
  # schedule:
  #   - cron: '0 0 * * 0'  # Exécuter chaque dimanche à minuit (UTC)
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Fetch upstream meryl_task branch
        run: git fetch upstream feature/meryl_task:upstream-meryl-task
      - name: Merge changes from upstream meryl_task branch into main
        run: |
          git checkout main
          git merge upstream-meryl-task --no-edit
      - name: Push changes to origin main
        run: git push origin main
